const zonas = {
  "Zona 01": {
    "type": "checkbox",
    "items": [
      "Barrio Valle Grande",
      "Barrio San José",
      "Barrio Aires de Montaña (Ex Conjunto 8)",
      "Barrio Aires del Oeste (Ex Conjunto 11)",
      "Loteo Puesta del Sol"
    ]
  },
  "Zona 02": {
    "type": "checkbox",
    "items": [
      "Los Sauces",
      "Villa San Miguel",
      "Loteo Universidad",
      "Loteo Páez Navarro"
    ]
  },
  "Zona 03": {
    "type": "checkbox",
    "items": [
      "Barrio Serranía del Sur",
      "Barrio Los Plátanos",
      "Barrio Ansilta",
      "Barrio Los Médanos",
      "Barrio Conjunto 2",
      "Barrio La Quebrada",
      "Loteo Rueda",
      "Barrio Alameda",
      "Barrio Franklin",
      "Barrio Malimán",
      "Barrio Río Blanco",
      "Barrio Los Caracoles",
      "Loteo Santa Catalina",
      "Barrio Portal del Sur",
      "Barrio Brisas del Sur",
      "Palmar del Cerro"
    ]
  },
  "Zona 04": {
    "type": "checkbox",
    "items": [
      "Barrio Güemes",
      "Barrio Hualilán",
      "Barrio Hugo Montaño",
      "Villa Don Pablo",
      "Barrio Cruz del Sur",
      "Barrio 23 de Mayo",
      "Barrio UDP IV",
      "Barrio Hualilán Sur",
      "Barrio Divino Niño Jesús",
      "Barrio SOEVA",
      "Barrio SUTYAGIF",
      "Barrio 2 de Agosto",
      "Villa Maureira",
      "Barrio República del Líbano",
      "Villa Arce",
      "Lote Hogar 22",
      "Villa Angélica"
    ]
  },
  "Zona 05": {
    "type": "checkbox",
    "items": [
      "12 de Diciembre",
      "Barrio San Expedito",
      "Barrio Victorino Ortega",
      "Loteo Deolinda",
      "Lote Hogar 18",
      "Barrio Aires de Florida 1 y 2",
      "Barrio Viñedos del Sur",
      "Barrio Medalla Milagrosa",
      "Barrio Empleados Plásticos",
      "Barrio Plásticos Ampliación (Ex Conjunto 3)",
      "Barrio Portal de Esperanza (Ex Conjunto 10)"
    ]
  },
  "Zona 06": {
    "type": "checkbox",
    "items": [
      "Barrio Ferroviario",
      "Barrio Victoria",
      "Villa Las Margaritas",
      "Barrio Ceramista",
      "Villa Hipódromo",
      "Villa San Cayetano",
      "Villa Palacio Balaguer",
      "Barrio Malvinas Argentinas",
      "Barrio Las Garzas",
      "Villa 11 de Noviembre",
      "Loteo Hogar 32",
      "Villa 17 de Agosto",
      "Barrio Juana Manso",
      "Lote Hogar 2 de Abril",
      "Loteo San José",
      "Barrio El Ciudadano",
      "Barrio UTA",
      "Barrio Procesa Sarmiento I",
      "Barrio Aires del Sur",
      "Barrio La Superiora",
      "Barrio AMESPU"
    ]
  },
  "Zona 07": {
    "type": "checkbox",
    "items": [
      "Barrio La Estación Sector 1 y 2",
      "Villa San Damián",
      "Villa Rodríguez Vila I",
      "Barrio Buenaventura Luna",
      "Lote Hogar 17"
    ]
  },
  "Zona 08": {
    "type": "checkbox",
    "items": [
      "Villa Estornell",
      "Villa Calandra",
      "Barrio San Luis",
      "Villa Italia",
      "Villa Ferla",
      "Barrio Salvador María del Carril",
      "Villa Las Rosas",
      "Barrio Marco",
      "Villa Congreso",
      "Villa Elsa",
      "Villa San Pedro",
      "Barrio Atlético",
      "Villa Maurín",
      "Villa Antonia",
      "Villa María",
      "Villa Libertador",
      "Villa Azocar",
      "Villa Lliver",
      "Villa Rachel",
      "Barrio Estado de Israel",
      "Barrio Gata de Gorgos",
      "Barrio Los Huarpes",
      "Barrio Los Manantiales"
    ]
  },
  "Zona 09": {
    "type": "checkbox",
    "items": [
      "Villa Laplagne",
      "Villa Yornet Funes",
      "Villa Novoa",
      "Barrio Capitán Lazo",
      "Villa Burón Alonso",
      "Villa Guzmán",
      "Villa Teresa",
      "Villa Ester",
      "Villa La Superiora",
      "Barrio Monseñor Orzali",
      "Loteo Vecher",
      "Villa Avellaneda",
      "Villa Mirarchi",
      "Barrio Presidencial Guillermo Rawson",
      "Barrio Héroes de Malvinas",
      "Barrio Mercedario",
      "Villa Cenobia Busto",
      "Villa Rodríguez Vila II"
    ]
  },
  "Zona 10": {
    "type": "checkbox",
    "items": [
      "Villa Krause"
    ]
  },
  "Zona 11": {
    "type": "checkbox",
    "items": [
      "Villa Echegaray",
      "Villa La Chacarilla",
      "Barrio Edilco",
      "Barrio Parque Sur",
      "Barrio Natania VII",
      "Loteo Paloma",
      "Barrio Libertad",
      "Villa Palacio",
      "Villa Franca",
      "Villa General Acha",
      "Villa Laprida",
      "Villa Los Paraísos",
      "Villa Lerga",
      "Villa San Cayetano"
    ]
  },
  "Zona 12": {
    "type": "checkbox",
    "items": [
      "Villa Fleury",
      "Barrio Sarmiento",
      "Barrio Obrero Rawson",
      "Villa Barón",
      "Villa Saiz",
      "Barrio Neuquén",
      "Villa Ágata de Cargo"
    ]
  },
  "Zona 13": {
    "type": "checkbox",
    "items": [
      "Barrio Floresta",
      "Barrio Presidente Sarmiento",
      "Barrio Oro Negro",
      "Barrio Los Horcones",
      "Barrio Licciardi",
      "Villa Rojas",
      "Villa Nueva Esperanza",
      "Barrio Sanjuaninos Héroes de Malvinas",
      "Villa Ballester",
      "Villa 12 de Octubre",
      "Villa Mascarell",
      "Barrio Empresa Mayo II",
      "Villa Giner",
      "Barrio Esperanza Mayo I",
      "Villa San Ricardo",
      "Lote Hogar 16",
      "Barrio 24 de Noviembre",
      "Barrio El Molle",
      "Loteo Don Vicente",
      "Loteo Fullana",
      "Barrio Mendoza",
      "Loteo Mascarell",
      "Loteo Montilla"
    ]
  },
  "Zona 14": {
    "type": "checkbox",
    "items": [
      "Barrio Tierra del Este",
      "Barrio Atalaya I",
      "Barrio CGT",
      "Barrio Atalaya II",
      "Loteo Don Matheo",
      "Loteo Heredia",
      "Barrio S.I.T.R.A.V.I.A.P",
      "Barrio Teniente Silva",
      "Barrio Sureño",
      "Barrio Reina Mora",
      "Barrio Parque Presidencial",
      "Barrio Los Horcones",
      "Barrio Rosendo",
      "Barrio Procesa Sarmiento",
      "Barrio Namaste I",
      "Barrio Namaste II",
      "Barrio Jorge Guardia",
      "Barrio Procesa Sarmiento 3",
      "Loteo Ulape",
      "Loteo Los Corredores",
      "Loteo Martínez"
    ]
  },
  "Zona 15": {
    "type": "checkbox",
    "items": [
      "Barrio José Miguel Escobar",
      "Barrio Portal del Sol",
      "Barrio Chacras de Cuyo",
      "Barrio Las Pircas",
      "Barrio Ejército de los Andes",
      "Barrio Sierras Moradas",
      "Barrio Luz y Fuerza",
      "Barrio Conjunto 1",
      "Barrio Conjunto 6",
      "Barrio Conjunto 5",
      "Villa José Dolores",
      "Loteo Esperanza",
      "Loteo Aguaribay",
      "Villa Pastor"
    ]
  },
  "Zona 16": {
    "type": "checkbox",
    "items": [
      "Villa Mascarell",
      "Villa Santo Domingo",
      "Barrio Cuesta del Viento",
      "Barrio Virgen de Fátima",
      "Barrio El Progreso",
      "Barrio STOTAC II",
      "Barrio AMECOM 4",
      "Barrio AMECOM 3",
      "Barrio 7 de Septiembre 3",
      "Barrio AMECOM 2",
      "Barrio AMECOM 1",
      "Barrio San Ignacio",
      "Barrio Padre Fanzolato",
      "Barrio Siete Colores I",
      "Barrio Senda",
      "Barrio Gruta de Fátima I",
      "Barrio Gruta de Fátima II",
      "Barrio Fanzolato Sur",
      "Barrio Obrero Textil",
      "Barrio El Laurel",
      "Barrio Medepyn",
      "Barrio San Guillermo"
    ]
  },
  "Resto de Rawson": {
    "type": "checkbox",
    "items": [
      "Barrio 24 de Noviembre",
      "Barrio Aires de Florida I",
      "Barrio Aires del Sur (Ex Don Juan)",
      "Barrio Alameda II",
      "Barrio Altas Cumbres (Ex Conjunto 8)",
      "Barrio Altos del Médano",
      "Barrio AMECOM",
      "Barrio AMECOM III",
      "Barrio AMECOM IV (Raúl Dolores Ávila)",
      "Barrio AMESPU",
      "Barrio ARA San Juan (Ex Conjunto II)",
      "Barrio Atlético",
      "Barrio Belgrano",
      "Barrio Brisas del Este (Conjunto N° 1)",
      "Barrio Buenaventura Luna",
      "Barrio Capitán Lazo",
      "Barrio Ceramista I",
      "Barrio Chacras de Cuyo",
      "Barrio Conjunto III",
      "Barrio Conjunto 10 (Portal de Esperanza)",
      "Barrio Cruz del Sur",
      "Barrio Cuesta del Viento",
      "Barrio Divino Niño Jesús",
      "Barrio Edilco",
      "Barrio Ejército de los Andes",
      "Barrio El Ciudadano Montilla",
      "Barrio El Molle",
      "Barrio El Progreso",
      "Barrio Empresa de Mayo",
      "Barrio Fanzolato Sur",
      "Barrio Ferroviario",
      "Barrio Floresta",
      "Barrio Fontana",
      "Barrio Foro de Abogados",
      "Barrio Franklin Rawson",
      "Barrio Héroes de Malvinas",
      "Barrio Hualilán I",
      "Barrio Hualilán Sur II",
      "Barrio Ing. Guardia",
      "Barrio Jacarandá",
      "Barrio Jardín 2 de Agosto",
      "Barrio Jorge Bubica",
      "Barrio Jorge Luis Borges (Ex CGT)",
      "Barrio José Miguel Escobar",
      "Barrio Juana Manso",
      "Barrio La Estación Sector I",
      "Barrio Las Praderas",
      "Barrio La Quebrada",
      "Barrio La Superiora Procrear",
      "Barrio Las Garzas",
      "Barrio Las Pircas",
      "Barrio Libertad",
      "Barrio Licciardi",
      "Barrio Lorenzo Miguel - 7 de Septiembre III Ord. N° 493-G",
      "Barrio Los Caracoles",
      "Barrio Los Horcones",
      "Barrio Los Horneros",
      "Barrio Los Manantiales",
      "Barrio Los Médanos",
      "Barrio Los Plátanos",
      "Barrio Los Plásticos II (Ampliación)",
      "Barrio Lote Hogar 2 de Abril",
      "Barrio Lote Hogar 16",
      "Barrio Lote Hogar 17",
      "Barrio Lote Hogar 18",
      "Barrio Lote Hogar 22",
      "Barrio Lote Hogar 32",
      "Barrio Loteo Rueda",
      "Barrio Luz y Fuerza",
      "Barrio Malimán",
      "Barrio Marco",
      "Barrio Malvinas Argentinas",
      "Barrio Martín Güemes",
      "Barrio Medalla Milagrosa",
      "Barrio Médano de Oro",
      "Villa Nueva Esperanza",
      "Villa San Vicente",
      "Villa La Estrella",
      "Villa Don Bosco",
      "Loteo Los Álamos",
      "Loteo San Gabriel",
      "Loteo La Victoria",
      "Loteo El Progreso",
      "Loteo Los Horneros",
      "Loteo La Ribera",
      "Loteo Ilegal Las Vertientes",
      "Loteo Ilegal El Molino"
    ]
  },
  "Médano de Oro": {
    "type": "text-input"
  },
  "Colonia Sarmiento": {
    "type": "text-input"
  },
  "Colonia Rodas": {
    "type": "text-input"
  },
  "Cerrillo Barbosa": {
    "type": "text-input"
  }
};